{"errorMessage": "PyAutoGUI can't be used in headless mode!", "errorType": "Exception", "requestId": "a5fad088-61a1-4a3a-9ec4-44556ae5a554", "stackTrace": ["  File \"/var/task/main.py\", line 40, in handler\n    driver.uc_gui_click_captcha()\n", "  File \"/var/lang/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py\", line 5064, in <lambda>\n    lambda *args, **kwargs: uc_gui_click_captcha(\n", "  File \"/var/lang/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py\", line 1354, in uc_gui_click_captcha\n    _uc_gui_click_captcha(\n", "  File \"/var/lang/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py\", line 1094, in _uc_gui_click_captcha\n    install_pyautogui_if_missing(driver)\n", "  File \"/var/lang/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py\", line 811, in install_pyautogui_if_missing\n    verify_pyautogui_has_a_headed_browser(driver)\n", "  File \"/var/lang/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py\", line 805, in verify_pyautogui_has_a_headed_browser\n    raise Exception(\n"]}